import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

// Read package.json for the app version (injected via define below).
const pkg = JSON.parse(
  readFileSync(fileURLToPath(new URL('./package.json', import.meta.url)), 'utf-8')
) as { version: string }

// Manual chunk grouping — keep heavy vendor libs out of the main entry chunk
// so the initial parse cost stays small.
const manualChunks = (id: string): string | undefined => {
  if (!id.includes('node_modules')) return undefined
  if (id.includes('/fabric/')) return 'fabric'
  if (id.includes('/lucide-react/')) return 'lucide'
  // fontkit (lazy-imported by textToOutline for glyph-level outlines) and its
  // runtime deps — brotli carries the woff2 decoder, the rest are its parsing
  // helpers. Nothing else in the app uses them, so one named async chunk keeps
  // them out of the entry bundle entirely.
  if (
    id.includes('/fontkit/') ||
    id.includes('/brotli/') ||
    id.includes('/restructure/') ||
    id.includes('/@swc/') ||
    id.includes('/fast-deep-equal/') ||
    id.includes('/unicode-properties/') ||
    id.includes('/unicode-trie/') ||
    id.includes('/dfa/') ||
    id.includes('/clone/') ||
    id.includes('/tiny-inflate/')
  )
    return 'fontkit'
  if (
    id.includes('/react-dom/') ||
    id.includes('/react/') ||
    id.includes('/scheduler/') ||
    id.includes('/zustand/')
  )
    return 'react'
  return undefined
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    // Progressive Web App — generates a service worker, web app manifest, and
    // a `virtual:pwa-register` module that the entry imports. With
    // `registerType: 'autoUpdate'` the SW picks up new builds in the
    // background; users get the next version on their next reload without a
    // prompt. Disabled in dev (default) so HMR keeps working.
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: [
        'favicon.svg',
        'icon-192.svg',
        'icon-512.svg',
        // Raster set (generated by `node scripts/generate-icons.mjs`) — cached
        // alongside the SVGs so install prompts and home-screen icons resolve
        // offline too.
        'icon-192.png',
        'icon-512.png',
        'apple-touch-icon.png',
        'icon-maskable-512.png',
      ],
      manifest: {
        name: 'Anchorworks',
        short_name: 'Vector',
        description:
          'AI-assisted vector graphics editor — Illustrator-class tooling, multi-format export, and direct output to laser cutters, plotters, and printers. Works offline.',
        categories: ['design', 'graphics', 'productivity'],
        theme_color: '#15151a',
        background_color: '#15151a',
        // `standalone` first: an earlier manifest declared
        // `window-controls-overlay` here, but the app drew no
        // titlebar-area-* drag region, so installed desktop PWAs could end up
        // with OS window controls overlapping the DOM menu bar. WCO is
        // dropped until the UI actually handles it; `standalone` stays the
        // baseline display mode and `minimal-ui` the fallback.
        display: 'standalone',
        display_override: ['standalone', 'minimal-ui'],
        scope: '/',
        start_url: '/',
        // OS associations: double-clicking an .svg / .vstudio.json (or
        // dragging onto the app icon) opens it directly in Anchorworks.
        // The `launch_handler` reuses the open window instead of spawning
        // duplicates on subsequent opens.
        launch_handler: { client_mode: ['navigate-existing', 'auto'] },
        file_handlers: [
          {
            action: '/',
            accept: {
              'image/svg+xml': ['.svg'],
              'application/json': ['.json', '.vstudio.json'],
            },
          },
        ],
        // Custom protocol so external apps can deep-link into Anchorworks
        // via `web+vector:` URIs (e.g. file-shell handlers, automation
        // scripts). The token is appended to the launch URL.
        protocol_handlers: [
          { protocol: 'web+vector', url: '/?open=%s' },
        ],
        icons: [
          // Raster icons (generated from the brand SVG by
          // `node scripts/generate-icons.mjs`) — the compatible set for iOS
          // home screens (Safari ignores SVG touch icons) and Android /
          // ChromeOS install prompts. The maskable entry is a separate,
          // inset-composed tile so adaptive-icon shells can crop freely
          // without clipping the brand mark.
          {
            src: 'icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
          // Pure-vector fallback — sized "any" so install banners can pick it
          // when no raster icon is provided.
          {
            src: 'favicon.svg',
            sizes: 'any',
            type: 'image/svg+xml',
          },
        ],
      },
      workbox: {
        // Cache every build artefact we ship. The jsPDF / fabric chunks can
        // be > 2 MB, so bump the per-file cap to 5 MB.
        globPatterns: ['**/*.{js,css,html,svg,ico,woff2,json}'],
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        runtimeCaching: [
          {
            // Google Fonts stylesheet (CSS lives on `fonts.googleapis.com`).
            urlPattern: ({ url }) => url.origin === 'https://fonts.googleapis.com',
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-stylesheets',
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Google Fonts binaries (woff2 served from `fonts.gstatic.com`).
            // Without this the stylesheet entry above caches only the CSS;
            // offline sessions still silently fall back to system fonts.
            urlPattern: ({ url }) => url.origin === 'https://fonts.gstatic.com',
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Inter stylesheet + font binaries (the `index.html` preconnects
            // to rsms.me for the Inter web font).
            urlPattern: ({ url }) => url.origin === 'https://rsms.me',
            handler: 'CacheFirst',
            options: {
              cacheName: 'rsms-inter',
              expiration: { maxEntries: 30, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Anthropic API — always prefer fresh, but tolerate offline by
            // falling back to no cached response (NetworkFirst with a tiny
            // timeout means the call resolves quickly on disconnect).
            urlPattern: ({ url }) => url.origin === 'https://api.anthropic.com',
            handler: 'NetworkFirst',
            options: {
              cacheName: 'anthropic-api',
              networkTimeoutSeconds: 10,
              expiration: { maxEntries: 0, maxAgeSeconds: 60 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  build: {
    rollupOptions: { output: { manualChunks } },
    // Rolldown-backed Vite also exposes rolldownOptions; configure identically
    // so we get the same behavior under either backend.
    rolldownOptions: { output: { manualChunks } },
    // The fabric (300 kB) and canvasEngine (721 kB) chunks are deliberate
    // manual-chunk groupings pulled by the first canvas paint — they are not
    // accidental bloat, so the default 500 kB warning is noise for them.
    // Keep the limit above their size so only genuinely oversized chunks
    // (the entry, until the i18n dictionary / MenuBar slim-downs land) warn.
    chunkSizeWarningLimit: 750,
  } as unknown as Record<string, unknown>,
})
