/**
 * One-shot migration: split src/lib/i18n.ts's inline en+zh dictionary into
 *   - src/lib/i18n.ts          -> keys with `{ en }` equal to the key collapse
 *                                  away entirely (t() falls back to the key,
 *                                  which IS the English text); only entries
 *                                  where en differs from the key survive in a
 *                                  small `enOverrides` table.
 *   - src/lib/i18n-zh.ts       -> the full key -> zh map, loaded lazily via
 *                                  dynamic import so it stays out of the entry
 *                                  chunk for English users.
 *
 * Idempotence: refuses to run if the legacy `const dict: Record<string,
 * Record<Lang, string>>` marker is absent (already migrated).
 */
const fs = require('fs');

const I18N = 'src/lib/i18n.ts';
const ZH = 'src/lib/i18n-zh.ts';

const src = fs.readFileSync(I18N, 'utf8');
const marker = 'const dict: Record<string, Record<Lang, string>> = {';
const start = src.indexOf(marker);
if (start < 0) {
  console.error('Legacy dict marker not found — i18n.ts already migrated? Nothing to do.');
  process.exit(1);
}
const end = src.indexOf('\n};', start);
if (end < 0) {
  console.error('Could not find the closing `};` of the dict.');
  process.exit(1);
}
const body = src.slice(start + marker.length, end);

// Entry forms (both terminate before an optional trailing comma); key/en/zh
// may each be single- OR double-quoted (the file mixes both styles):
//   'KEY': { en: 'EN', zh: 'ZH' },
//   "KEY": { en: "EN", zh: 'ZH' },
//   'KEY': {
//     en: 'EN',
//     zh: 'ZH',
//   },
const STR = String.raw`('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")`;
const re = new RegExp(
  STR + String.raw`\s*:\s*\{\s*en:\s*` + STR + String.raw`\s*,\s*zh:\s*` + STR + String.raw`\s*,?\s*\}`,
  'g',
);
const unquote = (s) => s.slice(1, -1);

let m;
let total = 0;
const enOverrides = [];
const zhDict = [];
const unparseable = [];
let consumed = 0;
let last = 0;
while ((m = re.exec(body)) !== null) {
  const [full, keyQ, enQ, zhQ] = m;
  const key = unquote(keyQ);
  const en = unquote(enQ);
  const zh = unquote(zhQ);
  total++;
  if (en !== key) enOverrides.push([key, en]);
  if (zh && zh !== key) zhDict.push([key, zh]);
  consumed += full.length;
  last = m.index + full.length;
}
// Anything substantial between entries (other than whitespace/commas/comments)?
const residue = body.slice(0, Math.min(last, body.length)).replace(re, '').replace(/[\s,]|\/\/[^\n]*|\/\*[\s\S]*?\*\//g, '');
if (residue.length > 0) {
  console.error('Unparseable residue inside dict (' + residue.length + ' chars): ' + residue.slice(0, 200));
  process.exit(1);
}
// Also scan the tail after the last match for stray entries the regex missed.
const tail = body.slice(last);
const tailEntries = tail.match(/^\s*'[^']*'\s*:/);
if (tailEntries) {
  console.error('Trailing unparsed entry-like text: ' + tail.slice(0, 120));
  process.exit(1);
}

const q = JSON.stringify;
const zhFile = `/**
 * Chinese dictionary — key is the English source string.
 *
 * Loaded LAZILY by src/lib/i18n.ts (dynamic import) so English users never
 * download it: it lives in its own code-split chunk (precached by the PWA
 * service worker, so offline switching still works). Generated by
 * scripts/split-i18n.cjs from the former inline dictionary — hand edits here
 * are fine, but the canonical workflow for new strings is documented in
 * i18n.ts's header.
 */

export const zhDict: Record<string, string> = {
${zhDict.map(([k, v]) => `  ${q(k)}: ${q(v)},`).join('\n')}
};
`;

const overrides = enOverrides.length
  ? `/** Keys whose English text differs from the key itself. */\nconst enOverrides: Record<string, string> = {\n${enOverrides.map(([k, v]) => `  ${q(k)}: ${q(v)},`).join('\n')}\n};\n`
  : `/** No entries deviate from the keys-are-English convention (yet). */\nconst enOverrides: Record<string, string> = {};\n`;

const newI18n = src.slice(0, start) + overrides + src.slice(end + 1);

fs.writeFileSync(ZH, zhFile);
fs.writeFileSync(I18N, newI18n);
console.log(`entries=${total} enOverrides=${enOverrides.length} zhDict=${zhDict.length}`);
console.log(`wrote ${ZH} (${zhFile.length} bytes) and rewrote ${I18N} (${newI18n.length} bytes, was ${src.length})`);
